server:
  port: 9090

spring:
  application:
    name: Tax_Management_System
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
  jackson:
    date-format: dd/MM/yyyy

